# Generated by Django 4.2.3 on 2024-04-12 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('school', models.CharField(max_length=50)),
                ('date_begin', models.DateField()),
                ('date_end', models.DateField()),
            ],
        ),
    ]
