# Generated by Django 4.2.3 on 2024-04-12 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informations', '0002_education'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificat',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
