# Generated by Django 4.2.3 on 2024-04-12 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informations', '0003_alter_certificat_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='school',
        ),
        migrations.AlterField(
            model_name='education',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
