# Generated by Django 4.2.3 on 2024-04-12 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informations', '0004_remove_education_school_alter_education_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='date_end',
            field=models.DateField(blank=True, null=True),
        ),
    ]
