# Generated by Django 4.2.3 on 2024-04-16 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('informations', '0005_alter_education_date_end'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='short_description',
        ),
        migrations.RemoveField(
            model_name='project',
            name='url',
        ),
    ]
