# Generated by Django 4.2.3 on 2024-04-16 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informations', '0006_remove_project_short_description_remove_project_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='professionnalprofile',
            old_name='content',
            new_name='description',
        ),
        migrations.AddField(
            model_name='professionnalprofile',
            name='address',
            field=models.CharField(default='teste', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='professionnalprofile',
            name='email',
            field=models.EmailField(default='teste', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='professionnalprofile',
            name='number',
            field=models.CharField(default='teste', max_length=20),
            preserve_default=False,
        ),
    ]
