# Generated by Django 4.2.3 on 2024-04-16 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informations', '0007_rename_content_professionnalprofile_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='school',
            field=models.CharField(default='teste', max_length=100),
            preserve_default=False,
        ),
    ]
