# Generated by Django 4.2.3 on 2024-04-16 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('informations', '0008_education_school'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
