# Generated by Django 4.2.3 on 2024-04-16 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informations', '0009_delete_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='professionnalprofile',
            name='github',
            field=models.URLField(default='teste'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='professionnalprofile',
            name='github_pseudo',
            field=models.CharField(default='test', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='professionnalprofile',
            name='linkedin',
            field=models.URLField(default='test'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='professionnalprofile',
            name='linkedin_pseudo',
            field=models.CharField(default='teste', max_length=50),
            preserve_default=False,
        ),
    ]
